const projects = [
    {name : "Chess",                            title : "Fear the pawn assassin!",                                              site : "chess",                                                                     siteType : "GitHub",    source : "chess.js",                type : "JavaScript",    date : "11/02/21",  warning : null          },
    {name : "Pong",                             title : "Sabotage your opponents in this classic pong!",                        site : "pong",                                                                      siteType : "GitHub",    source : "pong.js",                 type : "JavaScript",    date : "11/10/21",  warning : null          },
    {name : "Mouse On Canvas",                  title : "A simple technical test.",                                             site : "mouse_on_canvas",                                                           siteType : "GitHub",    source : "mouse_on_canvas.js",      type : "JavaScript",    date : "11/23/21",  warning : null          },
    {name : "Dave Busters",                     title : "A group project, with the amazing main character Dave!!!",             site : "dave_busters",                                                              siteType : "GitHub",    source : "dave_busters.js",         type : "JavaScript",    date : "02/23/22",  warning : null          },
    {name : "Memory",                           title : "A classic for all levels of skill.",                                   site : "memory",                                                                    siteType : "GitHub",    source : "memory.js",               type : "JavaScript",    date : "06/02/22",  warning : null          },
    {name : "Dodo Island",                      title : "Another group project. The dodos will return...",                      site : "dodo_island",                                                               siteType : "GitHub",    source : "dodo_island/",            type : "JavaScript",    date : "02/22/23",  warning : null          },
    {name : "Line Segment Intersections",       title : "Fun with math!",                                                       site : "line_segments",                                                             siteType : "GitHub",    source : "line_segments.js",        type : "JavaScript",    date : "06/11/23",  warning : null          },
    {name : "Ball Physics",                     title : "I believe the technical term is \"bounce angle.\"",                    site : "ball_physics",                                                              siteType : "GitHub",    source : "ball_physics.js",         type : "JavaScript",    date : "06/15/23",  warning : null          },
    {name : "Chip-8 Interpreter",               title : "Delving into how computers work at a low level. (future me here: no)", site : "chip-8",                                                                    siteType : "GitHub",    source : "chip-8.js",               type : "JavaScript",    date : "07/29/23",  warning : null          },
	{name : "Dodo's Quest: Staff of Arcania",   title : "The third group project, now with magical dodos.",                     site : "dodo_quest",                                                                siteType : "GitHub",    source : "dodo_quest/",             type : "JavaScript",    date : "02/22/24",  warning : null          },
];
